#!/usr/bin/env python3
"""
generate_mechanism_decks.py

Generates 6 PFLOTRAN input decks isolating the two multiphase controls
that are independent degrees of freedom in the flow model:

  Case C — PHASE PARTITIONING (4 new sims)
      Vary the injection CO2 mole fraction across the dissolved-to-scCO2
      continuum to test whether carbonation tracks the phase split.
      Values: 0.20, 0.40, 0.60, 0.80   (S1=0.04 and S2=0.99 already exist)

  Case D — BUOYANCY OVERRIDE (2 new sims)
      Vary the injection well vertical position (top vs bottom of formation)
      while keeping flow and chemistry fixed. If buoyancy override matters,
      top-injection should outperform bottom-injection.
      Positions: top (z=0-30m), bottom (z=70-100m)
                 (middle z=20-80m exists as the baseline)

  (A gas-residual-saturation sweep was considered as a test of the
   gas-water contact mechanism but was dropped: a uniform change in
   residual saturation alters the trapped-gas QUANTITY, not the gas-water
   contact MORPHOLOGY, and so does not isolate contact area. Gas-water
   contact is addressed structurally in the manuscript via the
   local-equilibrium dissolution argument.)

All cases use the S2 (scCO2) base configuration where the mechanism
matters most, with the single exception of Case C which is the full
mole-fraction continuum and includes both endmembers (S1 and S2).

Usage:
    python3 generate_mechanism_decks.py
Outputs:
    ./decks/caseC_phase_xfrac<value>.in   (Case C)
    ./decks/caseD_buoyancy_<position>.in  (Case D)
"""

import math
from pathlib import Path


# Baseline kinetic parameters from the verified Da-Pe Case A baseline
# log_k in mol/m^2/sec
BASE_KINETICS = {
    'forsterite_acid':   {'log_k':  -6.05, 'Ea': 70.5e3, 'alpha':  0.50},
    'forsterite_alk':    {'log_k':  -4.65, 'Ea': 66.3e3, 'alpha':  0.25},
    'anorthite_neutral': {'log_k':  -9.12, 'Ea': 74.5e3, 'alpha':  0.0},
    'anorthite_acid':    {'log_k':  -3.50, 'Ea': 69.4e3, 'alpha':  1.411},
    'diopside_neutral':  {'log_k': -11.11, 'Ea': 40.6e3, 'alpha':  0.0},
    'diopside_acid':     {'log_k':  -6.36, 'Ea': 96.1e3, 'alpha':  0.7},
    'calcite':           {'log_k':  -8.0,  'Ea': 48.0e3},
    'magnesite':         {'log_k': -10.0,  'Ea': 62.0e3},
    'siderite':          {'log_k':  -9.0,  'Ea': 52.0e3},
    'dolomite_ord':      {'log_k': -11.0,  'Ea': 55.0e3},
    'kaolinite':         {'log_k': -13.0,  'Ea': 62.0e3},
    'sio2_am':           {'log_k': -10.0,  'Ea': 50.0e3},
}


def build_deck(
        case_label,
        mole_fraction=0.99,        # Case C knob
        rate_g=5.0e-6,             # gas flow (m^3/s)
        rate_l=0.0,                # liquid flow (m^3/s)
        well_z_low=20.0,           # Case D knob
        well_z_high=80.0,          # Case D knob
        gas_residual_sat=0.10,     # Case E knob
        ):
    """Build a single deck with the given parameters."""
    kin = BASE_KINETICS

    # Format the well z-range carefully (default is 20.d0 - 80.d0)
    well_z_low_str = f"{well_z_low:.1f}d0"
    well_z_high_str = f"{well_z_high:.1f}d0"

    # Format rates with PFLOTRAN-friendly d-notation
    def fmt_rate(r):
        if r == 0.0:
            return "0.d0"
        # Convert to e-notation then swap e -> d
        return f"{r:.4e}".replace('e', 'd')
    rate_l_str = fmt_rate(rate_l)
    rate_g_str = fmt_rate(rate_g)

    deck = f"""# ==================================================================
# Mechanism Sweep — Case {case_label}
# mole_fraction = {mole_fraction}
# rate_l = {rate_l} m^3/s
# rate_g = {rate_g} m^3/s
# well z-range = [{well_z_low}, {well_z_high}] m
# gas residual saturation = {gas_residual_sat}
# Generated by generate_mechanism_decks.py
# ==================================================================

SIMULATION
  SIMULATION_TYPE SUBSURFACE
  PROCESS_MODELS
    SUBSURFACE_FLOW flow
      MODE GENERAL
      OPTIONS
        GAS_COMPONENT_FORMULA_WEIGHT 44.d0
      /
    /
    SUBSURFACE_TRANSPORT transport
      MODE GIRT
    /
  /
END

SUBSURFACE

NUMERICAL_METHODS FLOW
  TIMESTEPPER
    TS_ACCELERATION 8
    MAX_TS_CUTS 40
    MAX_STEPS 1000000
  /
  NEWTON_SOLVER
    ATOL 1.d-10
    RTOL 1.d-8
    STOL 1.d-30
    MAXIMUM_NUMBER_OF_ITERATIONS 40
    MAXF 200
  /
  LINEAR_SOLVER
    SOLVER ITERATIVE
  /
END

NUMERICAL_METHODS TRANSPORT
  TIMESTEPPER
    TS_ACCELERATION 8
    MAX_TS_CUTS 40
    MAX_STEPS 1000000
  /
  NEWTON_SOLVER
    ATOL 1.d-10
    RTOL 1.d-8
    STOL 1.d-30
    MAXIMUM_NUMBER_OF_ITERATIONS 40
  /
  LINEAR_SOLVER
    SOLVER ITERATIVE
  /
END

GRID
  TYPE STRUCTURED
  NXYZ 250 1 50
  DXYZ
    100@1.d0 50@3.d0 50@9.d0 50@26.d0
    1.d0
    50@2.d0
  /
END

MATERIAL_PROPERTY basalt
  ID 1
  POROSITY 0.15d0
  TORTUOSITY 0.3d0
  ROCK_DENSITY 2900.d0
  SPECIFIC_HEAT 900.d0
  THERMAL_CONDUCTIVITY_DRY 1.5d0
  THERMAL_CONDUCTIVITY_WET 2.0d0
  PERMEABILITY
    PERM_ISO 1.d-13
  /
  CHARACTERISTIC_CURVES cc1
/

CHARACTERISTIC_CURVES cc1
  SATURATION_FUNCTION VAN_GENUCHTEN
    ALPHA 1.d-4
    M 0.457d0
    LIQUID_RESIDUAL_SATURATION 0.15d0
    MAX_CAPILLARY_PRESSURE 1.d7
  /
  PERMEABILITY_FUNCTION MUALEM_VG_LIQ
    M 0.457d0
    LIQUID_RESIDUAL_SATURATION 0.15d0
  /
  PERMEABILITY_FUNCTION MUALEM_VG_GAS
    M 0.457d0
    GAS_RESIDUAL_SATURATION {gas_residual_sat}d0
    LIQUID_RESIDUAL_SATURATION 0.15d0
  /
END

FLUID_PROPERTY
  DIFFUSION_COEFFICIENT 1.d-9
/

CHEMISTRY
  PRIMARY_SPECIES
    H+
    Ca++
    Mg++
    Fe++
    Na+
    K+
    Al+++
    SiO2(aq)
    HCO3-
    SO4--
    Cl-
    O2(aq)
  /
  SECONDARY_SPECIES
    OH-
    CO2(aq)
    CO3--
    CaHCO3+
    CaCO3(aq)
    CaSO4(aq)
    MgHCO3+
    MgCO3(aq)
    Fe+++
    AlOH++
    Al(OH)2+
    Al(OH)3(aq)
    Al(OH)4-
    HSO4-
    H3SiO4-
  /
  PASSIVE_GAS_SPECIES
    CO2(g)
    O2(g)
  /
  MINERALS
    Forsterite
    Anorthite
    Diopside
    Calcite
    Magnesite
    Siderite
    Dolomite-ord
    Kaolinite
    SiO2(am)
  /
  MINERAL_KINETICS
    Forsterite
      PREFACTOR
        RATE_CONSTANT {kin['forsterite_acid']['log_k']:.4f}d0 mol/m^2-sec
        ACTIVATION_ENERGY {kin['forsterite_acid']['Ea']:.1f}
        PREFACTOR_SPECIES H+
          ALPHA {kin['forsterite_acid']['alpha']:.4f}d0
        /
      /
      PREFACTOR
        RATE_CONSTANT {kin['forsterite_alk']['log_k']:.4f}d0 mol/m^2-sec
        ACTIVATION_ENERGY {kin['forsterite_alk']['Ea']:.1f}
        PREFACTOR_SPECIES H+
          ALPHA {kin['forsterite_alk']['alpha']:.4f}d0
        /
      /
    /
    Anorthite
      PREFACTOR
        RATE_CONSTANT {kin['anorthite_neutral']['log_k']:.4f}d0 mol/m^2-sec
        ACTIVATION_ENERGY {kin['anorthite_neutral']['Ea']:.1f}
      /
      PREFACTOR
        RATE_CONSTANT {kin['anorthite_acid']['log_k']:.4f}d0 mol/m^2-sec
        ACTIVATION_ENERGY {kin['anorthite_acid']['Ea']:.1f}
        PREFACTOR_SPECIES H+
          ALPHA {kin['anorthite_acid']['alpha']:.4f}d0
        /
      /
    /
    Diopside
      PREFACTOR
        RATE_CONSTANT {kin['diopside_neutral']['log_k']:.4f}d0 mol/m^2-sec
        ACTIVATION_ENERGY {kin['diopside_neutral']['Ea']:.1f}
      /
      PREFACTOR
        RATE_CONSTANT {kin['diopside_acid']['log_k']:.4f}d0 mol/m^2-sec
        ACTIVATION_ENERGY {kin['diopside_acid']['Ea']:.1f}
        PREFACTOR_SPECIES H+
          ALPHA {kin['diopside_acid']['alpha']:.4f}d0
        /
      /
    /
    Calcite
      RATE_CONSTANT {kin['calcite']['log_k']:.4f}d0 mol/m^2-sec
      ACTIVATION_ENERGY {kin['calcite']['Ea']:.1f}
    /
    Magnesite
      RATE_CONSTANT {kin['magnesite']['log_k']:.4f}d0 mol/m^2-sec
      ACTIVATION_ENERGY {kin['magnesite']['Ea']:.1f}
    /
    Siderite
      RATE_CONSTANT {kin['siderite']['log_k']:.4f}d0 mol/m^2-sec
      ACTIVATION_ENERGY {kin['siderite']['Ea']:.1f}
    /
    Dolomite-ord
      RATE_CONSTANT {kin['dolomite_ord']['log_k']:.4f}d0 mol/m^2-sec
      ACTIVATION_ENERGY {kin['dolomite_ord']['Ea']:.1f}
    /
    Kaolinite
      RATE_CONSTANT {kin['kaolinite']['log_k']:.4f}d0 mol/m^2-sec
      ACTIVATION_ENERGY {kin['kaolinite']['Ea']:.1f}
    /
    SiO2(am)
      RATE_CONSTANT {kin['sio2_am']['log_k']:.4f}d0 mol/m^2-sec
      ACTIVATION_ENERGY {kin['sio2_am']['Ea']:.1f}
    /
  /
  DATABASE hanford.dat
  LOG_FORMULATION
  UPDATE_POROSITY
  UPDATE_PERMEABILITY
  OUTPUT
    ALL
    TOTAL
    PH
    MINERAL_VOLUME_FRACTION
  /
END

REGION all
  COORDINATES
    0.d0 0.d0 0.d0
    2000.d0 1.d0 100.d0
  /
END

REGION injection_well
  COORDINATES
    0.d0 0.d0 {well_z_low_str}
    20.d0 1.d0 {well_z_high_str}
  /
END

REGION outlet
  FACE EAST
  COORDINATES
    2000.d0 0.d0 0.d0
    2000.d0 1.d0 100.d0
  /
END

REGION obs_10m
  COORDINATE 10.d0 0.5d0 50.d0
/
REGION obs_50m
  COORDINATE 50.d0 0.5d0 50.d0
/
REGION obs_100m
  COORDINATE 100.d0 0.5d0 50.d0
/
REGION obs_250m
  COORDINATE 250.d0 0.5d0 50.d0
/
REGION obs_500m
  COORDINATE 500.d0 0.5d0 50.d0
/
REGION obs_1000m
  COORDINATE 1000.d0 0.5d0 50.d0
/

FLOW_CONDITION initial
  TYPE
    LIQUID_PRESSURE HYDROSTATIC
    MOLE_FRACTION DIRICHLET
    TEMPERATURE DIRICHLET
  /
  DATUM 0.d0 0.d0 100.d0
  LIQUID_PRESSURE 6.0d6
  MOLE_FRACTION 1.d-8
  TEMPERATURE 60.d0
/

FLOW_CONDITION outlet_bc
  TYPE
    LIQUID_PRESSURE HYDROSTATIC
    MOLE_FRACTION DIRICHLET
    TEMPERATURE DIRICHLET
  /
  DATUM 0.d0 0.d0 100.d0
  LIQUID_PRESSURE 6.0d6
  MOLE_FRACTION 1.d-8
  TEMPERATURE 60.d0
/

TRANSPORT_CONDITION initial_tc
  TYPE DIRICHLET_ZERO_GRADIENT
  CONSTRAINT_LIST
    0.d0 formation_water
  /
END

TRANSPORT_CONDITION injection_tc
  TYPE DIRICHLET
  CONSTRAINT_LIST
    0.d0 co2_water
  /
END

TRANSPORT_CONDITION outlet_tc
  TYPE DIRICHLET_ZERO_GRADIENT
  CONSTRAINT_LIST
    0.d0 formation_water
  /
END

CONSTRAINT formation_water
  CONCENTRATIONS
    H+        7.5d0   pH
    Ca++      2.0d-3  T
    Mg++      1.5d-3  T
    Fe++      5.0d-5  T
    Na+       1.0d-2  T
    K+        5.0d-4  T
    Al+++     1.0d-8  T
    SiO2(aq)  5.0d-4  T
    HCO3-     3.0d-3  T
    SO4--     1.0d-3  T
    Cl-       5.0d-3  T
    O2(aq)    1.0d-6  T
  /
  MINERALS
    Forsterite   0.05d0  5.d4 m^2/m^3
    Anorthite    0.30d0  5.d4 m^2/m^3
    Diopside     0.25d0  5.d4 m^2/m^3
    Kaolinite    0.25d0  1.d-2 m^2/m^3
    Calcite      0.0d0  5.d3 m^2/m^3
    Magnesite    0.0d0  5.d3 m^2/m^3
    Siderite     0.0d0  5.d3 m^2/m^3
    Dolomite-ord 0.0d0  5.d3 m^2/m^3
    SiO2(am)     0.0d0   1.d2 m^2/m^3
  /
END

CONSTRAINT co2_water
  CONCENTRATIONS
    H+        4.5d0   pH
    Ca++      1.0d-5  T
    Mg++      1.0d-5  T
    Fe++      1.0d-7  T
    Na+       1.0d-3  T
    K+        1.0d-4  T
    Al+++     1.0d-10 T
    SiO2(aq)  1.0d-6  T
    HCO3-     5.0d-2  T
    SO4--     1.0d-4  T
    Cl-       1.0d-3  T
    O2(aq)    5.0d-5  T
  /
END

FLOW_CONDITION injection
  TYPE
    RATE SCALED_VOLUMETRIC_RATE VOLUME
    MOLE_FRACTION DIRICHLET
    TEMPERATURE DIRICHLET
  /
  RATE LIST
    TIME_UNITS yr
    DATA_UNITS m^3/s m^3/s W
    0.d0 {rate_l_str} {rate_g_str} 0.d0
    30.d0 0.d0 0.d0 0.d0
  /
  MOLE_FRACTION LIST
    TIME_UNITS yr
    0.d0 {mole_fraction}d0
    30.d0 {mole_fraction}d0
  /
  TEMPERATURE 60.d0
/

STRATA
  MATERIAL basalt
  REGION all
END

INITIAL_CONDITION
  FLOW_CONDITION initial
  TRANSPORT_CONDITION initial_tc
  REGION all
END

BOUNDARY_CONDITION outlet_side
  FLOW_CONDITION outlet_bc
  TRANSPORT_CONDITION outlet_tc
  REGION outlet
END

SOURCE_SINK well
  FLOW_CONDITION injection
  TRANSPORT_CONDITION injection_tc
  REGION injection_well
END

OBSERVATION
  REGION obs_10m
/
OBSERVATION
  REGION obs_50m
/
OBSERVATION
  REGION obs_100m
/
OBSERVATION
  REGION obs_250m
/
OBSERVATION
  REGION obs_500m
/
OBSERVATION
  REGION obs_1000m
/

OUTPUT
  TIMES yr 0.5 1.0 2.0 5.0 10.0 20.0 30.0 50.0 75.0 100.0
  FORMAT HDF5
  VELOCITY_AT_CENTER
  VARIABLES
    LIQUID_PRESSURE
    GAS_SATURATION
    TEMPERATURE
    POROSITY
    PERMEABILITY_X
  /
  OBSERVATION_FILE
    PERIODIC TIME 30 d
  /
  MASS_BALANCE_FILE
    PERIODIC TIME 90 d
  /
  SNAPSHOT_FILE
    FORMAT HDF5
    PERIODIC TIME 365 d
  /
END

TIME
  FINAL_TIME 100.d0 yr
  INITIAL_TIMESTEP_SIZE 1.d-3 d
  MAXIMUM_TIMESTEP_SIZE 5.d0 d
/

END_SUBSURFACE
"""
    return deck


def main():
    out = Path('decks')
    out.mkdir(exist_ok=True)

    # ===================================================================
    # Case C — PHASE PARTITIONING (vary mole fraction)
    # ===================================================================
    # We use a mixed-injection setup (both liquid and gas rate) that lets
    # PFLOTRAN's phase equilibrium determine the actual phase split based
    # on the imposed mole fraction. Total volumetric injection is held
    # constant at 5e-6 m^3/s by partitioning between gas and liquid rates.
    print("=== Case C: PHASE PARTITIONING (vary mole fraction) ===")
    case_C_mole_fractions = [0.20, 0.40, 0.60, 0.80]
    # For each mole fraction, use a co-injection RATE of liquid + gas
    # corresponding to that phase split. Total volumetric: 5e-6 m^3/s
    for x in case_C_mole_fractions:
        # Proportion of injection that arrives as gas vs liquid
        # (use the mole fraction as a rough proxy; actual phase
        # partitioning is determined by PFLOTRAN's EOS)
        rate_g = 5.0e-6 * x
        rate_l = 5.0e-6 * (1.0 - x)
        deck = build_deck(
            case_label=f"C_phase_xfrac{x}",
            mole_fraction=x,
            rate_g=rate_g,
            rate_l=rate_l,
        )
        tag = f"{x:.2f}".replace('.', 'p')
        fname = out / f"caseC_phase_xfrac{tag}.in"
        fname.write_text(deck)
        print(f"  ✓ {fname.name}  (mole_frac={x}, rate_l={rate_l:.2e}, rate_g={rate_g:.2e})")

    # ===================================================================
    # Case D — BUOYANCY OVERRIDE (vary injection well z-position)
    # ===================================================================
    # Three injection positions:
    #   top    z = [0, 30]    — well in upper third
    #   middle z = [20, 80]   — baseline (already exists as Case A scco2_kappa1p0)
    #   bottom z = [70, 100]  — well in lower third
    print("\n=== Case D: BUOYANCY OVERRIDE (vary injection z-position) ===")
    case_D_positions = [
        ('top',    0.0,  30.0),
        ('bottom', 70.0, 100.0),
    ]
    for pos_name, z_low, z_high in case_D_positions:
        deck = build_deck(
            case_label=f"D_buoyancy_{pos_name}",
            mole_fraction=0.99,
            rate_g=5.0e-6,
            rate_l=0.0,
            well_z_low=z_low,
            well_z_high=z_high,
        )
        fname = out / f"caseD_buoyancy_{pos_name}.in"
        fname.write_text(deck)
        print(f"  ✓ {fname.name}  (well z = [{z_low}, {z_high}] m)")

    # ===================================================================
    # NOTE: A Case E (gas-residual-saturation sweep) was considered as a
    # test of the gas-water contact mechanism but was dropped. A uniform
    # change in residual saturation alters the trapped-gas QUANTITY, not
    # the gas-water contact MORPHOLOGY, so it does not isolate contact
    # area. Gas-water contact is instead addressed structurally in the
    # manuscript via the local-equilibrium dissolution argument (the
    # interfacial area does not enter the governing equations).
    # ===================================================================

    print(f"\nTotal decks generated: 6")
    print(f"  Case C (phase partitioning): 4")
    print(f"  Case D (buoyancy override):  2")
    print(f"\nOutput directory: {out.absolute()}")


if __name__ == "__main__":
    main()
